apiVersion: v1
kind: Pod
metadata:
  name: ex2
  namespace: practica3
spec:
  containers:
    - name: args2
      image: alpine
      command: ["echo"]
      args:
        - "$(MSG1)"
        - "$(MSG2)"
      env:
        - name: MSG1
          valueFrom:
            configMapKeyRef:
              name: ex2cm
              key: msg1
        - name: MSG2
          valueFrom:
            configMapKeyRef:
              name: ex2cm
              key: msg2
