apiVersion: v1
kind: Pod
metadata:
  name: ex3
  namespace: practica3
spec:
  containers:
    - name: args3
      image: alpine
      command: ["echo"]
      args:
        - "$(MSG1)"
      env:
        - name: MSG1
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: apikey
