apiVersion: v1
kind: PersistentVolume
metadata:
  name: ex4-pv
  namespace: practica3
spec:
  capacity:
    storage: 60Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /work