apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: backend
spec:
  capacity:
    storage: 1.2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /