apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: practica2inst3
spec:
  # modifica las réplicas según tu caso de uso
  replicas: 2
  selector:
    matchLabels:
      app: web-cache
  template:
    metadata:
      labels:
        app: web-cache
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-cache
            topologyKey: "kubernetes.io/hostname" 
      containers:
        - name: cache-server
          image: redis
          ports:
          - containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 20
