apiVersion: v1
kind: Pod
metadata:
  name: web-1
  namespace: practica2inst1
  labels:
    tier: frontend
    porpouse: training
spec:
  containers:
    - name: nginx-server
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 6
        periodSeconds: 3
      resources:
        requests:
          memory: "100Mi"
    - name: cache-server
      image: redis
  nodeSelector:
    size: Medium
